version: 2.0
jobs:
  terraform_plan:
   docker:
      - image: hashicorp/terraform:0.11.7 
   steps:
      - checkout
      - run:
          name: Init and Apply
          command: |
            #env
            #echo '====='
            TF_WS="$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH" 
            echo "Check formatting:"
            terraform fmt -diff -check && echo "Formatting OK!"
            echo "Init Terraform:"
            #terraform init -backend-config="key=$STATE_PATH/terraform.tfstate"
            # https://www.terraform.io/docs/backends/config.html#partial-configuration
            terraform init -backend-config="key=circleci.tfstate"
            # select workspace if it already exists
            terraform workspace new $TF_WS || terraform workspace select $TF_WS
            echo "Validate code:"
            terraform validate && echo "Code validation OK!"
            echo "Make a plan:"
            terraform plan
            terraform apply -auto-approve
            #uncomment the next 3 lines in order to remove the resources created above and rerun.
            terraform destroy -auto-approve    # Uncomment to remove resources
            terraform workspace select default # Can't delete current workspace
            terraform workspace delete $TF_WS  # Delete stub tfstate in S3
            
   
workflows:
  version: 2
  dev_plan:
   jobs:
      - terraform_plan
