version: 2.0
jobs:
  terraform_plan:
   docker:
      - image: hashicorp/terraform:0.11.7
   steps:
      - run:
          name: Init and Apply
          command: |
            #terraform init
            terraform init -backend-config="bucket=$BUCKET" -backend-config="key=terraform.tfstate" -backend-config="region=us-west-2"
            terraform plan
   
workflows:
  version: 2
  dev_plan:
    jobs:
      - terraform_plan
