version: 2.0
jobs:
  terraform_plan:
   docker:
      - image: hashicorp/terraform:0.11.7 
   steps:
      - checkout
      - run:
          name: Init and Apply
          command: |
            pwd
            ls -la
            #testing circleci env variables
            echo ${CIRCLE_BRANCH}
            echo ${CIRCLE_PROJECT_REPONAME}
            sed 's/GENERIC/${CIRCLE_PROJECT_REPONAME/g' backend.tf.save > backend.tf

            #git clone https://github.com/msisler99/circleci-terraform.git
            #cd circleci-terraform
            
            terraform init

            terraform plan
            
            terraform apply -auto-approve
        
            #uncomment the next line in order to remove the resources created above and rerun.
            terraform destroy -auto-approve
            
   
workflows:
  version: 2
  dev_plan:
   jobs:
      - terraform_plan
