version: 2.0
jobs:
  terraform_plan:
   docker:
      - image: hashicorp/terraform:0.11.7 
   steps:
      - checkout
      - run:
          name: Init and Apply
          command: |
            pwd
            ls -la
            #testing circleci env variables
            echo "branch "${CIRCLE_BRANCH}
            echo "project repo name "${CIRCLE_PROJECT_REPONAME}
            echo "pull request "${CI_PULL_REQUEST}
            
            echo ${CI_PULL_REQUEST} > temp.txt
            cat temp.txt
            
            #https://github.com/msisler99/circleci-terraform/pull/1
            
            BUCKET=$(sed 's/^.\{19\}//' temp.txt)
            
            sed 's/GENERIC/'$BUCKET'/' backend.tf.save > backend.tf
            cat backend.tf

            #git clone https://github.com/msisler99/circleci-terraform.git
            #cd circleci-terraform
            
            terraform init

            terraform plan
            
            terraform apply -auto-approve
        
            #uncomment the next line in order to remove the resources created above and rerun.
            terraform destroy -auto-approve
            
   
workflows:
  version: 2
  dev_plan:
   jobs:
      - terraform_plan
