version: 2.0
jobs:
  terraform_plan:
   docker:
      - image: hashicorp/terraform:0.11.7 
   steps:
      - checkout
      - run:
          name: Init and Apply
          command: |
          
            echo "${CI_PULL_REQUEST}" > temp1.txt
            echo "Pull request -"$CI_PULL_REQUEST
            echo "branch - "$CIRCLE_BRANCH
            
            
            sed 's/^.\{19\}//' temp1.txt > temp2.txt
            
            sed -e "s/GENERIC/$(sed 's:/:\\/:g' temp2.txt)/" backend.tf.save > backend.tf
            cat backend.tf
            
            terraform init

            terraform plan
            
            terraform apply -auto-approve
        
        
            #uncomment the next line in order to remove the resources created above and rerun.
            #terraform destroy -auto-approve
            
   
workflows:
  version: 2
  dev_plan:
   jobs:
      - terraform_plan
