version: 2.0
jobs:
  terraform_plan:
   docker:
      - image: hashicorp/terraform:0.11.7 
   steps:
      - run:
          name: Init and Apply
          command: |
            git clone https://github.com/msisler99/circleci-terraform.git
            pwd
            ls -la
            cd circleci-terraform
            terraform -version
            pwd
            ls -la
            terraform init
            ls -la
            terraform plan
            terraform apply -auto-approve
            ls -la
            terraform destroy -auto-approve
   
workflows:
  version: 2
  dev_plan:
   jobs:
      - terraform_plan
