version: 2.0
jobs:
  terraform_plan:
   docker:
      - image: hashicorp/terraform:0.11.7 
   steps:
      - run:
          name: Init and Apply
          command: |
            git clone https://github.com/msisler99/circleci-terraform.git
            pwd
            ls -la
            cd circleci-terraform
            pwd
            ls -l
            terraform init
   
workflows:
  version: 2
  dev_plan:
   jobs:
      - terraform_plan
