version: 2.0
jobs:
  terraform_plan:
   docker:
      - image: hashicorp/terraform:0.11.7 
   steps:
      - run:
          name: Init and Apply
          command: |
            pwd
            ls -la
            terraform init
   
workflows:
  version: 2
  dev_plan:
   jobs:
      - terraform_plan
